print('============================================')
print()
print('Nombre         : EduTrack')
print()
print('Tipo           : Plataforma web')
print()
print('Fundador       : Ana López')
print()
print('Ciudad         : Tuxtla Gutiérrez, Chiapas')
print()
print('Mercado        : Estudiantes universitarios')
print()
print('Modelo         : Suscripción mensual')
print()
print('Precio mensual : $149 MXN')
print()
print('Usuarios año 1 : 200')
print()
print('Lanzamiento est: Septiembre 2026')
print()
print('============================================')
print()
print('Problema:')
print()
print('Los estudiantes pierden seguimiento de tareas')
print()
print('y fechas clave por no tener una herramienta')
print()
print('centralizada para sus proyectos escolares.')
print()
print('Solución:')
print()
print('Plataforma para registrar tareas, avances')
print()
print('y fechas con recordatorios automáticos.')