print('------------------------------------')
print()
print('        COMPROBANTE DE PAGO         ')
print()
print('------------------------------------')
print()
print('Cliente  : Gladis Janeth Ara Santiz')
print()
print('Servicio : NotaPro')
print()
print('Plan     : Mensual')
print()
print('------------------------------------')
print()
print('Subtotal : $149.00')
print()
print('IVA 16%  : $23.84')
print()
print('TOTAL    : $172.84')
print()
print('------------------------------------')
print()
print('      Gracias por tu preferencia    ')
print()
print('------------------------------------')